### ISSUE TITLE
[1.19.2] Game crashes due to a ClassCastException when closing quest menu while in a crafting station

### ISSUE THREAD

**Issue by reiramirez** [ClaudiusMinimus/CreatePotatoUltimate#10]
### Describe the Bug

The game crashes because of an unhandled ClassCastException when closing the quest menu opened from the inventory while currently in a crafting station.

### Reproduction Steps

1. Open a crafting station.
2. Click the quest menu button on the top-left.
3. Close the quest menu.

### Expected Result

Game shouldn't crash. Maybe the ClassCastException should be handled somewhere? It could also be a class loading issue.

### Crash Report or Log

https://crashy.net/64b4332d-abcd-4e56-b975-5a7e16ac1029

### Operating System

Windows 11

### Modpack Name and Version

Create on a Potato PC Ultimate 1.19.2-4.11.0

### Minecraft Version

1.19.2

### Forge Version

43.2.8

**Comment by TheosCreation** [comment]
Updated crafting station should fixed it
