### ISSUE TITLE
[1.19.2-4.12.0] ShiftedLib 1.1.1 is not server compatible

### ISSUE THREAD

**Issue by TigerWalts** [ClaudiusMinimus/CreatePotatoUltimate#11]
### Describe the Bug

ShiftedLib loads a client-only class on server start and causes a crash.

Downgrading the following mods allows the server to start:

- ShiftedLib 1.0.2
- WitherProofed 2.7.4

Players are able to join even with the newer versions of these mods on their client.

### Reproduction Steps

1. Start the modpack as a server.

### Expected Result

No crash

### Operating System

N/A

### Modpack Name and Version

Create on a Potato PC Ultimate 1.19.2 4.12.0

### Minecraft Version

1.19.2

### Forge Version

43.3.5

**Comment by TheosCreation** [comment]
thanks very much for easy fix i have downgraded the mods
