### ISSUE TITLE
[1.19.2-4.12.0] Server files contain client only mod oculus

### ISSUE THREAD

**Issue by JulianVennen** [ClaudiusMinimus/CreatePotatoUltimate#12]
### Describe the Bug

The server files of this version contain the client-only mod oculus, which causes the server to crash.

### Reproduction Steps

1. Download the server files
2. Try to start the server

### Expected Result

The server should start without any errors.

### Crash Report or Log

https://mclo.gs/WNdPIRa

### Operating System

Linux

### Modpack Name and Version

Create on a Potato PC: Ultimate 1.19.2-4.12.0

### Minecraft Version

1.19.2

### Forge Version

43.3.5

**Comment by JulianVennen** [comment]
This mod is still included in 4.12.0

**Comment by JulianVennen** [comment]
Same problem in 4.13.0

**Comment by TheosCreation** [comment]
can you tell me the name of the mod file as i cannot find oculus

**Comment by TheosCreation** [comment]
ok i think i found it OCD1.19.2-0.1_alpha.jar and is not meant to be on a server
