### ISSUE TITLE
Blaze Mesh in Questline

### ISSUE THREAD

**Issue by EternalFlam3-14** [ClaudiusMinimus/CreatePotatoUltimate#4]
### Describe the Bug

It seems Blaze Mesh are supposed to be obtained before going to the Nether, but there are no pre-Nether Blaze Rod sources.
Fel Pumpkins spawn weaker Blaze that only drop Blaze Powder, which cannot be crafted into Blaze Rods.
The weaker Blaze may still drop Spawn Eggs, which appear to be included in the loot tables of this modpack. However, in my opinion, relying on those eggs seems excessive, especially considering the standard drop rate of Blaze Rods. A crafting recipe or another Blaze Rod source might be a better option.

### Reproduction Steps

1. Start a survival world (easier to reproduce on Skyblock)
2. Attempt to follow the questline
3. Use a Fel Pumpkin to spawn a weak Blaze
4. Only receive Blaze Powder

### Expected Result

Either a method of crafting rods out of powder, or a source of Blaze Rods before entering the Nether. Or the quest to be repositioned as a post-Nether Portal quest.

### Operating System

Windows 10

### Modpack Name and Version

Create on a Potato PC Ultimate 1.19.2-4.0.0

### Minecraft Version

1.19.2

### Forge Version

36.2.0

### Other Mods

Haven't added anything to the modpack.

### Additional Context

I am playing on a standard survival world, so I do have a way to reach the Nether before I get the Blaze Meshes, but it seems impossible for access to the Nether on a Skyblock world, at least through the Blaze Mesh route, which is the route the questline seems to suggest taking.

**Comment by ClaudiusMinimus** [comment]
Was my mistake. Garden of Glass modifies Botania and only requires blaze dust to make the blaze mesh. I should have looked closer. I have added this to my Trello project page 
![image](https://github.com/ClaudiusMinimus/CreatePotatoUltimate/assets/17887664/2dc792c5-b6c7-4f92-851a-2e94f6f4ddcb)

**Comment by ClaudiusMinimus** [comment]
Here is a [link](https://legacy.curseforge.com/minecraft/modpacks/create-on-a-potato/files/4591577) to the patch file
