### ISSUE TITLE
[1.19.2] KubeJS allowAsyncStreams causes CME from SilentGear while loading server scripts

### ISSUE THREAD

**Issue by TigerWalts** [ClaudiusMinimus/CreatePotatoUltimate#9]
### Describe the Bug

The bug has already been reported here:

- https://github.com/SilentChaos512/Silent-Gear/issues/617

---

When the KubeJS `recipes` event is run non-thread-safe code from SilentGear may also be run.

If `allowAsyncStreams` is enabled in `kubejs/config/common.properties` then this may lead to ConcurrentModificationException. 

This is handled and logged but it will result in scripts failing. Recipes changes and other things will not have happened.

---

## Workaround

Setting `allowAsyncStreams` in `kubejs/config/common.properties` to `false` avoids the CME.

### Reproduction Steps

1. Start a server running the modpack
   Client may also be affected
2. Joining the server will display an error in the chat log
3. Check the KubeJS log for the error

### Expected Result

Scripts to run without error

### Operating System

N/A

### Modpack Name and Version

Create on a Potato PC Ultimate 1.19.2 4.11.1

### Minecraft Version

1.19.2

### Forge Version

43.2.8

**Comment by TheosCreation** [comment]
ok thanks for letting me know has fixed the issue an will be inplace in next update
